version: '3.8'
services:
  postgresql:
    image: postgres:latest
    ports:
      - 9999:9999
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=appName
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef